version: '3.8'

services:
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "80:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
    restart: unless-stopped
    volumes:
      - ./webapp:/usr/src/app
      - /usr/src/app/node_modules

networks:
  default:
    driver: bridge

# You can add volumes if needed
# volumes:
#   my_data:
